server:
  port: 7777
  error:
    include-stacktrace: always

logging:
  level:
    root: DEBUG
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security: TRACE
    logging.level.org.hibernate.SQL: INFO
    com.zaxxer.hikari: ERROR
    org.postgresql: ERROR

springdoc:
  auth-types:
    auth-header-enabled: true
    client-credentials-enabled: true
    authorization-code-enabled: true
  auth-oauth:
    token-url: http://localhost:7777/oauth2/token
    authorization_url: http://localhost:7777/oauth2/authorize
    refresh-url: http://localhost:7777/oauth2/token
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true
    path: /v3/api-docs

spring:
  application:
    name: j-sso
  mvc:
    static-path-pattern: /static/**
    cors:
      configs:
        - pattern: /**
          allowed-origins: "http://127.0.0.1:8080,http://localhost:8080,http://localhost:7778"
          allowed-headers: "*"
          exposed-headers: "*"
          allowed-methods: "*"
          allow-credentials: true
  web:
    resources:
      static-locations: classpath:static
  session:
    timeout: 1800                 # Время жизни сессии (в секундах)
    redis:
      flush-mode: on_save         # Указываем, когда изменения сеанса записываются в хранилище (immediate или on_save)
      namespace: j-sso:session    # Пространство имен для ключей, используемых для хранения сессий.
      save-mode: on_set_attribute # Определяет в какой момент происходит сохранение изменений сессии (on_set_attribute, on_get_attribute, always)
  data:
    redis: # Настраиваем подключение к Redis
      client-type: lettuce        # Указываем тип клиента Redis (jedis или lettuce)
      database: 0                 # Указываем номер БД Redis
      host: localhost             # Хост подключения
      port: 6379                  # Порт подключения
      password: qwerty12345678    # Пароль подключения
      lettuce: # Настраиваем пул подключений клиента lettuce
        pool:
          max-active: 16          # Максимальное количество подключений в пуле
          max-idle: 8             # Минимальное количество "idle" подключений в пуле
  liquibase:
    enabled: false  # Указать true, если необходимо сделать накат скриптов БД при запуске приложения
    change-log: classpath:database/db.changelog.yaml
    contexts: prod, dev
  datasource:
    url: "jdbc:postgresql://localhost:5435/j-sso"
    username: "user"
    password: "user"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-j-sso"
      register-mbeans: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:7777
        introspection-endpoint: /oauth2/token-info
        authentication-success-url: http://localhost:7777/home # было http://localhost:7777/
        custom-handler-header-name: J-Sso-Next-Location
        authorization-ttl: 720000
        authorization-consent-ttl: 720000
      client:
        registration:
          github:
            clientId: ${JSSO_GITHUB_CLIENT_ID}
            clientSecret: ${JSSO_GITHUB_CLIENT_SECRET}

          google:
            clientId: ${JSSO_GOOGLE_CLIENT_ID}
            clientSecret: ${JSSO_GOOGLE_CLIENT_SECRET}
            # Добавил эти scopes чтобы использовать именно OAuth2.
            # Иначе по умолчанию добавляется scope = openid и тогда взаимодействие идёт по протоколу OpenID Connect
            scope:
              - email
              - profile

          yandex:
            provider: yandex
            clientId: ${JSSO_YANDEX_CLIENT_ID}
            clientSecret: ${JSSO_YANDEX_CLIENT_SECRET}
            redirect-uri: http://localhost:7777/login/oauth2/code/yandex
            authorizationGrantType: authorization_code
            clientName: Yandex

        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

yandex-avatar-url: https://avatars.yandex.net/get-yapic/{avatarId}/islands-retina-50

d-email:
  email: ${JSSO_SMTP_EMAIL}
  password: ${JSSO_SMTP_EMAIL_PASSWORD}
  host: smtp.jino.ru
  port: 587

otp-store:
  cookie-name: dl-sso-temporary-session
  cookie-domain: localhost
  cookie-max-age: 180

---
spring:
  config:
    activate:
      on-profile: production
  liquibase:
    contexts: prod

---
spring:
  config:
    activate:
      on-profile: development
  liquibase:
    contexts: prod, dev