server:
  port: 9001
logging:
  level:
    root: DEBUG
    javax.management: ERROR
    org.springframework.security.web.FilterChainProxy: DEBUG

springdoc:
  auth:
    auth-header-enabled: true
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true
    path: /v3/api-docs

spring:
  application:
    name: j-service
  mvc:
    cors:
      configs:
        - pattern: /**
          allowed-origins: "http://localhost:7778"
          allowed-headers: "*"
          exposed-headers: "*"
          allowed-methods: "*"
          allow-credentials: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: test-client
          client-secret: test-client
          introspection-uri: http://localhost:7777/oauth2/token-info